//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Client du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpeditionHelper_SOL.Resources.Views.Client {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpeditionHelper_SOL.Resources.Views.Client.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string Titre
        {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une Client.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en prod..
        /// </summary>
        public static string Nom
        {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string Action
        {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string Code
        {
            get
            {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string Adresse
        {
            get
            {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string AddAddressSuccess
        {
            get
            {
                return ResourceManager.GetString("AddAddressSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string EmptyText
        {
            get
            {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string EmptyAddressCode
        {
            get
            {
                return ResourceManager.GetString("EmptyAddressCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string AddressCodeExisting
        {
            get
            {
                return ResourceManager.GetString("AddressCodeExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string EmptyGroup
        {
            get
            {
                return ResourceManager.GetString("EmptyGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string FailAddAddress
        {
            get
            {
                return ResourceManager.GetString("FailAddAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string EditAddressSuccess
        {
            get
            {
                return ResourceManager.GetString("EditAddressSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string FailEditAddress
        {
            get
            {
                return ResourceManager.GetString("FailEditAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string DeleteAddressSuccess
        {
            get
            {
                return ResourceManager.GetString("DeleteAddressSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string FailDeleteAddress
        {
            get
            {
                return ResourceManager.GetString("FailDeleteAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string Groupe
        {
            get
            {
                return ResourceManager.GetString("Groupe", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string Sauvegarder
        {
            get
            {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string MsgDeletePart1
        {
            get
            {
                return ResourceManager.GetString("MsgDeletePart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string MsgDeletePart2
        {
            get
            {
                return ResourceManager.GetString("MsgDeletePart2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string Codeadresse
        {
            get
            {
                return ResourceManager.GetString("Codeadresse", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string TitleDelete
        {
            get
            {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string TitleAdd
        {
            get
            {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string TitleEdit
        {
            get
            {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descriptif.
        /// </summary>
        public static string MsgDeletePart3
        {
            get
            {
                return ResourceManager.GetString("MsgDeletePart3", resourceCulture);
            }
        }
    }
}
