//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpeditionHelper_SOL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpeditionHelper_SOLEntities : DbContext
    {
        public ExpeditionHelper_SOLEntities()
            : base("name=ExpeditionHelper_SOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ADRESSE> TB_ADRESSE { get; set; }
        public virtual DbSet<TB_CLIENT> TB_CLIENT { get; set; }
        public virtual DbSet<TB_ETAPE> TB_ETAPE { get; set; }
        public virtual DbSet<TB_EXPEDITION> TB_EXPEDITION { get; set; }
        public virtual DbSet<TB_INCOTERM> TB_INCOTERM { get; set; }
        public virtual DbSet<TB_Liaison> TB_Liaison { get; set; }
        public virtual DbSet<TB_LIEN> TB_LIEN { get; set; }
        public virtual DbSet<TB_LOG> TB_LOG { get; set; }
        public virtual DbSet<TB_PROCEDURE_EXPEDITION> TB_PROCEDURE_EXPEDITION { get; set; }
        public virtual DbSet<TB_VERSION> TB_VERSION { get; set; }
    }
}
