//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpeditionHelper_SOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ADRESSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ADRESSE()
        {
            this.TB_ETAPE = new HashSet<TB_ETAPE>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string CodeAdresse { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string GroupId { get; set; }
    
        public virtual TB_CLIENT TB_CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ETAPE> TB_ETAPE { get; set; }
    }
}
