//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpeditionHelper_SOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EXPEDITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EXPEDITION()
        {
            this.TB_PROCEDURE_EXPEDITION = new HashSet<TB_PROCEDURE_EXPEDITION>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public Nullable<int> Avancement { get; set; }
        public string Incoterm { get; set; }
        public string NumeroBonDeLivraison { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROCEDURE_EXPEDITION> TB_PROCEDURE_EXPEDITION { get; set; }
    }
}
