//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     EtapeDefaut du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpeditionHelper_SOL.Resources.Views.EtapeDefaut {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index()
        {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpeditionHelper_SOL.Resources.Views.EtapeDefaut.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string BtnAjouter
        {
            get
            {
                return ResourceManager.GetString("BtnAjouter", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une EtapeDefaut.
        /// </summary>
        public static string Etape
        {
            get
            {
                return ResourceManager.GetString("Etape", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string Explication
        {
            get
            {
                return ResourceManager.GetString("Explication", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en prod..
        /// </summary>
        public static string Numero
        {
            get
            {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string PlaceholderEtape
        {
            get
            {
                return ResourceManager.GetString("PlaceholderEtape", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de mise en prod..
        /// </summary>
        public static string Titre
        {
            get
            {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string TitreCard
        {
            get
            {
                return ResourceManager.GetString("TitreCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string Action
        {
            get
            {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalLinkReadTitre
        {
            get
            {
                return ResourceManager.GetString("ModalLinkReadTitre", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalLinkWriteTitre
        {
            get
            {
                return ResourceManager.GetString("ModalLinkWriteTitre", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalLinkNom
        {
            get
            {
                return ResourceManager.GetString("ModalLinkNom", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalLinkUrl
        {
            get
            {
                return ResourceManager.GetString("ModalLinkUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalLinkLien
        {
            get
            {
                return ResourceManager.GetString("ModalLinkLien", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalUpdateStepTitre
        {
            get
            {
                return ResourceManager.GetString("ModalUpdateStepTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalUpdateStepBtnEditer
        {
            get
            {
                return ResourceManager.GetString("ModalUpdateStepBtnEditer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalDeleteStepTitre
        {
            get
            {
                return ResourceManager.GetString("ModalDeleteStepTitre", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalDeleteStepBtnDelete
        {
            get
            {
                return ResourceManager.GetString("ModalDeleteStepBtnDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ErrorFunction
        {
            get
            {
                return ResourceManager.GetString("ErrorFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string UpdateOrderFunction
        {
            get
            {
                return ResourceManager.GetString("UpdateOrderFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteFunction
        {
            get
            {
                return ResourceManager.GetString("DeleteFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string FailDeleteFunction
        {
            get
            {
                return ResourceManager.GetString("FailDeleteFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string AddStepFunction
        {
            get
            {
                return ResourceManager.GetString("AddStepFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string FailAddStepFunction
        {
            get
            {
                return ResourceManager.GetString("FailAddStepFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string EmptyTexte
        {
            get
            {
                return ResourceManager.GetString("EmptyTexte", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string AddLinkFunction
        {
            get
            {
                return ResourceManager.GetString("AddLinkFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string FailAddLinkFunction
        {
            get
            {
                return ResourceManager.GetString("FailAddLinkFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteLinkFunction
        {
            get
            {
                return ResourceManager.GetString("DeleteLinkFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string FailDeleteLinkFunction
        {
            get
            {
                return ResourceManager.GetString("FailDeleteLinkFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string UpdateStep
        {
            get
            {
                return ResourceManager.GetString("UpdateStep", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string FailUpdateStep
        {
            get
            {
                return ResourceManager.GetString("FailUpdateStep", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string Incoterm
        {
            get
            {
                return ResourceManager.GetString("Incoterm", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ModalDeleteTexte
        {
            get
            {
                return ResourceManager.GetString("ModalDeleteTexte", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string BtnDocument
        {
            get
            {
                return ResourceManager.GetString("BtnDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string SelectItemTitle
        {
            get
            {
                return ResourceManager.GetString("SelectItemTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string Profil
        {
            get
            {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string PlaceholderNewGroup
        {
            get
            {
                return ResourceManager.GetString("PlaceholderNewGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string AddGroupCardTitle
        {
            get
            {
                return ResourceManager.GetString("AddGroupCardTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteGroupCardTitle
        {
            get
            {
                return ResourceManager.GetString("DeleteGroupCardTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string PlaceholderSelectGroup
        {
            get
            {
                return ResourceManager.GetString("PlaceholderSelectGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteMessagePart1
        {
            get
            {
                return ResourceManager.GetString("DeleteMessagePart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteMessagePart2
        {
            get
            {
                return ResourceManager.GetString("DeleteMessagePart2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string NoGroupSelected
        {
            get
            {
                return ResourceManager.GetString("NoGroupSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteGroup
        {
            get
            {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string AddGroup
        {
            get
            {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string DeleteGroupFail
        {
            get
            {
                return ResourceManager.GetString("DeleteGroupFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string AddGroupFail
        {
            get
            {
                return ResourceManager.GetString("AddGroupFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string ImpossibleDeleteGroup
        {
            get
            {
                return ResourceManager.GetString("ImpossibleDeleteGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string UpdateGroupSuccess
        {
            get
            {
                return ResourceManager.GetString("UpdateGroupSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string EditGroupCardTitle
        {
            get
            {
                return ResourceManager.GetString("EditGroupCardTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actuellement en prod..
        /// </summary>
        public static string BtnModifier
        {
            get
            {
                return ResourceManager.GetString("BtnModifier", resourceCulture);
            }
        }
    }
}
